### ISSUE TITLE
Operations.copyCollection fetchFrom incorrectly assigned?

### ISSUE THREAD

**Issue by relwell** [whitepages/solrcloud_manager#1]
```
java -jar solrcloud_manager-assembly-1.4.0.jar copycollection --collection example --fromCollection example --zk localhost:9983 --fromCluster 192.168.99.1:9983
Operation: 
	FetchIndex: from: http://127.0.1.1:7574/solr, fromCore: lee_shard1_replica1, toCore: lee_shard1_replica1
Seem reasonable? [y]> y
Applied FetchIndex: from: http://127.0.1.1:7574/solr, fromCore: lee_shard1_replica1, toCore: lee_shard1_replica1
Verified FetchIndex: from: http://127.0.1.1:7574/solr, fromCore: lee_shard1_replica1, toCore: lee_shard1_replica1
SUCCESS
```

It looks like this is basically copying the same node onto itself. This doesn't seem right. I'm interested in using this library for migrating collections between ZK clusters (e.g. between testing environments).

Please let me know if this is an easy fix, otherwise I'm happy to fork and do it myself.

**Comment by relwell** [comment]
Running Solr 5.5.0 if it makes a difference. I'm seeing some notes in the source code around Solr 5.4.

**Comment by relwell** [comment]
This looks like it's an outcome of using the example deployment, which runs its own zookeeper and two instances on the same server.

**Comment by randomstatistic** [comment]
Great to hear this sounds useful to you!  I have not tried it with 5.5 yet, although cross version compatibility has been pretty good so far. Please let me know how your experience goes.
